export const mockedUser = {
  id: 0,
  crmid: '12x11',
  firstname: 'Sergei',
  lastname: 'Emelianov',
  description: 'Here is changed description second',
  account_id: '11x6',
  account_name: '',
  title: 'Director',
  department: 'Management',
  email: 'se@sergeyem.ru',
  created_at: '0001-01-01T00:00:00Z',
  updated_at: '0001-01-01T00:00:00Z',
  is_active: false,
  mailingcity: 'Cheboksary',
  mailingstreet: 'Bulvar Yunosti, 3',
  mailingcountry: 'Russia',
  othercountry: 'Russia',
  mailingstate: 'Chuvashia',
  mailingpobox: '',
  othercity: 'Cheboksary',
  otherstate: 'Chuvashia',
  mailingzip: '428010',
  otherzip: '428010',
  otherstreet: 'Bulvar Yunosti, 3',
  otherpobox: '',
  image: '',
  imageattachmentids: '12x42',
  imagecontent: '',
  phone: '+4915211100235',
};
