import { LineItem, LineItemFinalDetails } from '../../invoice/types';
import { Currency } from '../../misc/types/currency.ts';

export type SalesOrder = {
  salesorder_no: string;
  subject: string;
  potential_id: string;
  customerno: string;
  quote_id: string;
  vtiger_purchaseorder: string;
  contact_id: string;
  duedate: string;
  carrier: string;
  pending: string;
  sostatus: string;
  txtAdjustment: string;
  salescommission: string;
  exciseduty: string;
  hdnGrandTotal: number;
  hdnSubTotal: number;
  hdnTaxType: string;
  hdnDiscountPercent: string;
  hdnDiscountAmount: string;
  hdnS_H_Amount: string;
  account_id: string;
  assigned_user_id: string;
  createdtime: string;
  modifiedtime: string;
  modifiedby: string;
  currency_id: string;
  conversion_rate: string;
  bill_street: string;
  ship_street: string;
  bill_city: string;
  ship_city: string;
  bill_state: string;
  ship_state: string;
  bill_code: string;
  ship_code: string;
  bill_country: string;
  ship_country: string;
  bill_pobox: string;
  ship_pobox: string;
  description: string;
  terms_conditions: string;
  enable_recurring: string;
  recurring_frequency: string;
  start_period: string;
  end_period: string;
  payment_duration: string;
  invoicestatus: string;
  fromsite: string;
  pre_tax_total: string;
  hdnS_H_Percent: string;
  spcompany: string;
  created_user_id: string;
  source: string;
  starred: boolean;
  region_id: string;
  id: string;
  label: string;
  'shipping_&_handling': number;
  'shipping_&_handling_shtax1': number;
  currency: Currency;
  LineItems: LineItem[];
  LineItems_FinalDetails: {
    [key: string]: LineItemFinalDetails;
  };
};
