name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci --force
      - name: build production project
        run: npm run build
        if: always()
      - name: linting typescript
        run: npm run lint
        if: always()
      - name: validation
        run: npm run validate
      - name: unit testing
        if: always()
        run: npm run test
      - name: check types
        run: npm run check-types
        if: always()
      - name: check format
        run: npm run check-format
        if: always()